# fly.toml app configuration file generated for micropost150108 on 2023-06-13T07:02:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "micropost150108"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_NAME = "micropost"
  APP_URL = "https://micropost150108.fly.dev"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "postgres"
  DB_HOST = "db.hpocfcrchtghujtqzvnm.supabase.co"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
